### ISSUE TITLE
Error on startup when Pre-Load All is enabled; works normally with it disabled

### ISSUE THREAD

**Issue by NANI-ship-it** [EtienneLamoureux/TQVaultAE#279]
TQVaultAE fails to start when "Pre-Load All Vault And Character Files" is enabled, resulting in the following error:

![TQVaultAE_Error](https://user-images.githubusercontent.com/59906490/72458362-1d732780-37d1-11ea-9901-20745a10664f.jpg)

When the Pre-Load is disabled, everything seems to work correctly and I'm able to load all characters and stashes. Also after restarting TQVaultAE after the error, it automatically asks if Pre-Load should be disabled, so it seems this is already known to cause issues.

I'm using Good Old Games version of TQ:AE 2.8b with Ragnarök and Atlantis expansions, no mods or any alterations. English language. Can this issue have something to do with the Good Old Games version?

Relevant lines from the log:
```
2020-01-15 19:38:17,235 [1] INFO  TQVaultAE.GUI.MainForm [(null)] - TQVaultAE Initialization !
2020-01-15 19:38:18,026 [1] ERROR TQVaultAE.GUI.MainForm [(null)] - resourcesLoaded = True
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at TQVaultAE.GUI.MainForm.LoadAllFiles()
   at TQVaultAE.GUI.MainForm.LoadResources(BackgroundWorker worker, DoWorkEventArgs e)
   at TQVaultAE.GUI.MainForm.BackgroundWorker1_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by NANI-ship-it** [comment]
Yes, this happens with TQVaultAE version 3.4.0.

**Comment by AlexSnowLeo** [comment]
I also got this error at startup. It is easy to reproduce. On Windows, the Eng language must be installed and the game has a different one (in my case, RU)

**Comment by dru4a3** [comment]
![изображение](https://user-images.githubusercontent.com/17232055/79504080-ec59fb80-803a-11ea-8cc0-2c24c1b70484.png)
Double "\" in game path can help

**Comment by Soheil777** [comment]
> Yes, this happens with TQVaultAE version 3.4.0.

hi my dear brother
sorry i am so simple user i find your software from 
https://www.youtube.com/watch?v=OjMvhLMbHNg

for first time i open it i have a lot of error but after couple time rest look like fix but problem is: i create new Vault with clicking on the Maintain Vault Files but after i close software and open it again all of them gone
why? i use last version and my game in 2.9
i wish you created video for help people about problem and error
