### ISSUE TITLE
111Gb of logs, trying to read file program log goes BRRRRRR

### ISSUE THREAD

**Issue by HighbornHellest** [EtienneLamoureux/TQVaultAE#463]
End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy1.get_Value()
   at TQVaultAE.Domain.Helpers.LazyConcurrentDictionary2.<>cDisplayClass3_2.<AddOrUpdateAtomic>b3()
   at System.Lazy`1.CreateValue()

it couldn't read file: winsys.dxg in character folder

it's this for many many many many lines.
![image](https://user-images.githubusercontent.com/15896727/184449045-e7f229d7-2e15-44cb-bff2-dcaabd09b645.png)

In like 10 seconds it produced a ONE GIGABYTE logifel
Recommendation: it tries to access resource every few seconds and if it fails 5-10 times, it stops

Insanity proof: 
![image](https://user-images.githubusercontent.com/15896727/184449254-4157a491-d19e-4a24-b222-4660da224c5e.png)

**Comment by hguy** [comment]
Hi @HighbornHellest,
Either your stash file is corrupted, or maybe you swaped it with a stash file from a mod.
In the first case we can't do anything, in the second case, put back the regular stash file and switch TQVault to your Mod from the settings window.
![image](https://user-images.githubusercontent.com/31834707/184627706-b52ebee1-9094-47eb-87af-14912ce6ada2.png)
It could be because you swap your TQPath to a modded version of the database.arz also.

**Comment by hguy** [comment]
Reproduction impossible without the user save file directory.

**Comment by hguy** [comment]
Won't fix
